docs: growing-blog 2차 설계 작성
growing-pains/growing-blog pull request #2
Opened 2022-05-14 05:28 UTC by Dayglow0926

2022-05-15 14:44 UTC, Sung-jin commented
파일 확장자명을 md 로 변경해주세요.
미리 보기가 보이질 않습니다.

진행하신 설계 노션을 들어가면 권한 없다고 나와서 확인이 불가능합니다.

유저를 추후에 구현하는 형태로 진행해도 괜찮을 듯 싶습니다.
유저의 경우 고려해야 할 부분과 설정해야 할 부분이 많아서 생각보다 많이 복잡합니다.

우선 게시글 작성, 조회, 수정 정도를 구현해서 프로젝트 뼈대를 구현한 후 유저를 붙이는 것도 좋은 방법일 것 같습니다.

2022-05-15 14:46 UTC, Sung-jin requested changes

2022-05-15 14:46 UTC, Sung-jin commented on design/2nd design
> +![img.png](img.png)
파일 확장자명을 md 로 변경해주세요.
미리 보기가 보이질 않습니다.

진행하신 설계 노션을 들어가면 권한 없다고 나와서 확인이 불가능합니다.
변경된 파일에 해당하는 이미지가 푸시가 안된 것 같습니다.

유저를 추후에 구현하는 형태로 진행해도 괜찮을 듯 싶습니다.
유저의 경우 고려해야 할 부분과 설정해야 할 부분이 많아서 생각보다 많이 복잡합니다.

우선 게시글 작성, 조회, 수정 정도를 구현해서 프로젝트 뼈대를 구현한 후 유저를 붙이는 것도 좋은 방법일 것 같습니다.

2022-05-15 15:16 UTC, gwanhyeon commented on design/2nd design
> +![img.png](img.png)
노션 권한설정 부분 처리가 누락되어 있는것 같고, 위에 @Sung-jin 가 말한 것 처럼 유저보다는 게시글 우선적으로 기능 개발을 진행해도 좋을 것 같습니다~

유저부분 권한, 보안 인증 처리까지 하게 되면 시간 소요가 많이 된 경험이 있네요..!

2022-05-16 12:26 UTC, Dayglow0926 commented on design/2nd design
> +![img.png](img.png)
말씀해주신 파일 확장자 변경과 이미지 업로드 완료하였습니다.

유저 내용에 대해서는 말씀해주신 대로 기본적인 기능을 완료 후 추가로 작업을 진행하겠습니다.

2022-05-16 14:56 UTC, gwanhyeon reviewed
유저기능은 식별 컬럼만 잘 처리해서 게시글 위주로 개발한 후 유저 보안,인증 부분을 덧붙여 나가면 좋을 것 같습니다. 유저 부분은 생각해야할 부분이 많아 보여요. 저 역시도 일단 유저 부분은 배제시키고 그외 기능적인 부분을 먼저 기획해 나갈 생각입니다.

2022-05-17 13:59 UTC, merged