프로젝트 생성 및 게시글 엔티티 생성
growing-pains/growing-blog pull request #3
Opened 2022-05-21 01:58 UTC by Dayglow0926

2022-05-23 04:00 UTC, Sung-jin requested changes

2022-05-23 04:00 UTC, Sung-jin commented on growingblog/.gitignore
> +.vscode/
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

.idea/libraries 의 경우 프로젝트 마다 repository 에 올릴지 사용자가 알아서 하면 된다라고 하네요.

maven/gradle 등으로 자동으로 라이브러리가 추가되고 그런다면 제외 시키는 걸 추천해드립니다.
버전이 변경되거나 dependency 가 변경될 때 마다 해당 파일들도 계속 추가가 되기 때문에 리뷰가 힘들어질 것 같습니다.

2022-05-23 04:00 UTC, Sung-jin commented on growingblog/src/main/java/com/example/growingblog/domain/BlogPost.java
> +
jpa 를 라이브러리에 추가하셨는데, `@Entity` 로 동작하기 위해서는 빈 constructor 가 필요합니다 [링크](https://moztiq.medium.com/no-default-constructor-for-entity-jpa-f59a5588e71c)

관련된 내용을 더 찾아보시는걸 추천합니다.

아무런 생성자가 없다면 기본적으로 빈 생성자를 생성을 해주지만, 다른 생성자를 추가할 경우 기본으로 생성되는 no argument 생성자는 별도로 생성하지 않으면 생성되지 않습니다.
그리고 `@Entity` 에서 기본 생성자는 protected 로 선언해 주는게 좋습니다. [링크](https://erjuer.tistory.com/106)
해당 내용도 더 찾아보시는걸 추천합니다.

```java
protected BlogPost() {}
// 또는
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```

2022-05-24 07:51 UTC, Dayglow0926 commented on growingblog/.gitignore
> +.vscode/
감사합니다. 해당 내용 참고하여 진행하겠습니다.

2022-05-25 15:45 UTC, Dayglow0926 commented on growingblog/src/main/java/com/example/growingblog/domain/BlogPost.java
> +
감사합니다 전달 주신 내용 확인 후 내용 수정하였습니다.

2022-05-28 00:29 UTC, merged